name: "Build with nix"

on:
  push:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        # I would like if there was a ubuntu-latest-arm but alas
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3
      # We don't use a store cache so as to catch hash mismatches in the Gleam deps
      - run: nix build -L
